{
 "title": "jmeter-jmx-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(jmx_exporter_build_info,job)"
    }
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(jmx_exporter_build_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(jmx_exporter_build_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "query_result(\"$server:$port\")"
    }
   },
   { "name": "port_node_exporter", "query": "${VAR_PORT_NODE_EXPORTER}" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "Утилизация CPU (%) процессом.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"$host\", job=\"$job\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{instance=\"$server:$port_node_exporter\", job=\"node_exporter\"}[$__rate_interval]))",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Resident Memory %",
   "type": "gauge",
   "description": "Фактическое использование памяти (%) процессом.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$host\", job=\"$job\"} / process_virtual_memory_bytes{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "resident_memory"
    }
   ]
  },
  {
   "title": "Heap %",
   "type": "gauge",
   "description": "Утилизация Heap (куча) (%).",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", instance=\"$host\", job=\"$job\"} / jvm_memory_max_bytes{area=\"heap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "NonHeap %",
   "type": "gauge",
   "description": "Утилизация NonHeap (стек) (%).",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", instance=\"$host\", job=\"$job\"} / jvm_memory_max_bytes{area=\"nonheap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Count Classes",
   "type": "stat",
   "description": "Количество классов, которые в данный момент загружены в приложении.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COUNT"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "table",
   "description": "Ссылка отображает период от начала записи до выбранной точки.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$host\", job=\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "description": "Версия JVM.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{instance=\"$host\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Время от начала записи до выбранной точки.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$host\", job=\"$job\"}"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "Утилизация CPU (%) процессом.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$host\", job=\"$job\"}[$__rate_interval]) / scalar(count(count(node_cpu_seconds_total{instance=\"$server:$port_node_exporter\", job=\"node_exporter\"}) by (cpu)))",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Resident Memory %",
   "type": "timeseries",
   "description": "Фактическое использование памяти (%) процессом.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$host\", job=\"$job\"} / process_virtual_memory_bytes{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "CPU (millicore)",
   "type": "timeseries",
   "description": "Утилизация CPU (millicore) процессом.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$host\", job=\"$job\"}[$__rate_interval]) * 1000",
     "legendFormat": "USED"
    },
    {
     "expr": "scalar(count(count(node_cpu_seconds_total{instance=\"$server:$port_node_exporter\", job=\"node_exporter\"}) by (cpu))) * 1000",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "description": "VIRTUAL_MEMORY - общий объем памяти, который может потребоваться процессу.  \nRESIDENT_MEMORY - фактическое использование памяти процессом.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "RESIDENT_MEMORY"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "VIRTUAL_MEMORY"
    }
   ]
  },
  { "title": "Heap / NonHeap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Heap %",
   "type": "timeseries",
   "description": "Утилизация Heap (куча) (%).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", instance=\"$host\", job=\"$job\"} / jvm_memory_max_bytes{area=\"heap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "NonHeap %",
   "type": "timeseries",
   "description": "Утилизация NonHeap (стек) (%).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", instance=\"$host\", job=\"$job\"} / jvm_memory_max_bytes{area=\"nonheap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "description": "USED - используемая память.  \nCOMMITTED - доступная память.  \nMAX - максимальный размер памяти.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "NonHeap",
   "type": "timeseries",
   "description": "USED - используемая память.  \nCOMMITTED - доступная память.  \nMAX - максимальный размер памяти.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"nonheap\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "GC Count",
   "type": "timeseries",
   "description": "Количество сборок мусора (GC).  \nG1 Young Generation - младшее поколение (малая сборка / minor GC).  \nG1 Old Generation - старшее поколение (полная сборка / full GC).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{instance=\"$host\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "description": "Время выполнения сборки мусора (GC).  \nG1 Young Generation - младшее поколение (малая сборка / minor GC).  \nG1 Old Generation - старшее поколение (полная сборка / full GC).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"$host\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "timeseries",
   "description": "Пул памяти для новых объектов (Eden Space).  \nОтносится к Young Generation - младшее поколение.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"G1 Eden Space\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"G1 Eden Space\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"G1 Eden Space\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "timeseries",
   "description": "Пул памяти для выживших объектов (Survivor Space).  \nОтносится к Young Generation - младшее поколение.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"G1 Survivor Space\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"G1 Survivor Space\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"G1 Survivor Space\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "G1 Old Gen",
   "type": "timeseries",
   "description": "Пул памяти для долгоживущих объектов (Old Gen).  \nОтносится к Old Generation - старшее поколение.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"G1 Old Gen\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"G1 Old Gen\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"G1 Old Gen\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "CURRENT - пользовательские потоки, которые используются для задач переднего плана и ввода-вывода в приложении. JVM ждёт завершения их выполнения.  \nDAEMON - потоки с низким приоритетом, которые работают в фоновом режиме и выполняют задачи, например, сбор мусора, или предоставляют услуги пользовательским потокам.  \nКогда все пользовательские потоки завершают выполнение, JVM автоматически завершает демонические потоки, даже если они ещё выполняются.  \nDEADLOCKED - потоки, которые долго ждут друг друга и не могут сделать дальнейший прогресс.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "CURRENT"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "DAEMON"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=\"$host\"}",
     "legendFormat": "DEADLOCKED"
    }
   ]
  },
  {
   "title": "Current Threads State",
   "type": "timeseries",
   "description": "NEW - создан, но ещё не запущен.  \nRUNNABLE - активный поток, либо готов к выполнению и ждёт процессорного времени.  \nBLOCKED - ждёт захвата блокировки монитора, которую держит другой поток.  \nWAITING - ждёт, пока другой поток выполнит определённое действие.  \nTIMED WAITING - ждёт определённое количество времени, пока другой поток выполнит определённое действие.\nTERMINATED - завершил выполнение или был прерван из-за исключения или ошибки.  \nUNKNOWN - состояние потока неизвестно.  \n\nWAITING - состояние, в котором поток ждёт, пока другой поток выполнит конкретное действие. Например, если вызвать Object.wait() на объекте, то поток будет ждать, пока другой поток вызовет Object.notify() или Object.notifyAll() на этом объекте.  \nTIMED WAITING  - состояние, в котором поток ждёт, пока другой поток выполнит действие в течение определённого времени. Например, если вызвать Thread.sleep() или Object.wait(timeout). В этом состоянии поток будет находиться до тех пор, пока не истечёт указанный срок или другой поток не уведомит его.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_state{instance=\"$host\", job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Native Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "description": "Пул памяти для хранения метаданных классов.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"Metaspace\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"Metaspace\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"Metaspace\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Direct Buffer Pool",
   "type": "timeseries",
   "description": "Пул памяти из которого можно выполнить прямое чтение.  \nИспользуется для операций ввода-вывода.  \nUSED -  используемая память буферного пула.  \nCAPACITY - общий объем данного буферного пула в байтах.\nused_buffers - используемые буферы из данного пула буферов JVM. Это целое число.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{pool=\"direct\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_buffer_pool_capacity_bytes{pool=\"direct\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "CAPACITY"
    },
    {
     "expr": "jvm_buffer_pool_used_buffers{pool=\"direct\", instance=\"$host\"}",
     "legendFormat": "used_buffers"
    }
   ]
  },
  {
   "title": "Mapped Buffer Pool",
   "type": "timeseries",
   "description": "Пул памяти для FileChannel-инстанций.  \nПозволяет загрузить часть файла прямо в память, чтобы позже к ней можно было обратиться. Это даёт значительный прирост производительности, если нужно много раз читать содержимое файла. Последующие чтения будут использовать содержимое файла из памяти, а не загружать данные с диска каждый раз, когда они нужны.  \nUSED -  используемая память буферного пула.  \nCAPACITY - общий объем данного буферного пула в байтах.\nused_buffers - используемые буферы из данного пула буферов JVM. Это целое число.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_used_bytes{pool=\"mapped\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_buffer_pool_capacity_bytes{pool=\"mapped\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "CAPACITY"
    },
    {
     "expr": "jvm_buffer_pool_used_buffers{pool=\"mapped\", instance=\"$host\"}",
     "legendFormat": "used_buffers"
    }
   ]
  },
  {
   "title": "CodeHeap Non-Nmethods",
   "type": "timeseries",
   "description": "Пул памяти, содержащий буферы компилятора и интерпретатор байт-кода.  \nИспользуется для работы JIT (just-in-time compilation).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"CodeHeap 'non-nmethods'\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"CodeHeap 'non-nmethods'\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"CodeHeap 'non-nmethods'\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "CodeHeap Non-Profiled Nmethods",
   "type": "timeseries",
   "description": "Пул памяти содержит полностью оптимизированные методы, которые живут долго.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"CodeHeap 'non-profiled nmethods'\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"CodeHeap 'non-profiled nmethods'\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"CodeHeap 'non-profiled nmethods'\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "CodeHeap Profiled Nmethods",
   "type": "timeseries",
   "description": "Пул памяти содержит слегка оптимизированные методы, которые могут не понадобиться ещё раз.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"CodeHeap 'profiled nmethods'\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "USED"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{pool=\"CodeHeap 'profiled nmethods'\", instance=\"$host\", job=\"$job\"}",
     "legendFormat": "COMMITTED"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{pool=\"CodeHeap 'profiled nmethods'\", instance=\"$host\"}",
     "legendFormat": "MAX"
    }
   ]
  }
 ]
}